version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: lasvega7LAMA
    ports:
      - "3307:3306"

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"


  user-service:
    image: user-service:latest
    container_name: user-service
    ports:
      - "8081:8080"


  lab-service:
    image: lab-service:latest
    container_name: lab-service
    ports:
      - "8082:8080"


  analysis-service:
    image: analysis-service:latest
    container_name: analysis-service
    ports:
      - "8083:8080"


  frontend:
    image: frontend-app:latest
    container_name: frontend
    ports:
      - "4200:80"


