version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: lasvega7LAMA
      MYSQL_USER: root
    ports:
      - "3306:3306"

  api-gateway:
    image: my-app/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  user-service:
    image: my-app/user-service:latest
    container_name: user-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db

  lab-service:
    image: my-app/lab-service:latest
    container_name: lab-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db

  analysis-service:
    image: my-app/analysis-service:latest
    container_name: analysis-service
    ports:
      - "8083:8080"
    depends_on:
      - mysql-db

  frontend:
    image: my-app/frontend:latest
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway

volumes:
  mysql-data:
